package cn.zest.sso.server.config;

import lombok.Data;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * ZestSSO 配置属性。
 */
@Data
@Component
@ConfigurationProperties(prefix = "zest.sso")
public class SsoProperties {

    private String issuer = "http://localhost:9000";
    private Jwt jwt = new Jwt();
    private Security security = new Security();
    @Data
    public static class Bootstrap {
        private boolean resetDefaultPassword = true;
    }

    private Bootstrap bootstrap = new Bootstrap();
    private Token token = new Token();

    @Data
    public static class Jwt {
        private String keyId = "zest-sso-key-1";
        private String privateKeyPath;
        private String publicKeyPath;
        /** 未配置 PEM 路径时，自动生成并持久化到此目录（开发/单机生产） */
        private String autoGenerateDir;
    }

    @Data
    public static class Audit {
        private boolean archiveEnabled = true;
        /** 保留天数，超期物理删除（等保建议 ≥180） */
        private int retentionDays = 180;
    }

    @Data
    public static class Backchannel {
        private int maxRetries = 3;
        private int retryDelaySeconds = 60;
    }

    @Data
    public static class Webhooks {
        private boolean enabled = false;
        private String signingSecret;
        private List<String> endpoints = List.of();
        private int maxRetries = 5;
        private int retryDelaySeconds = 30;
        private List<String> events = List.of("LOGIN_SUCCESS", "LOGIN_FAILURE", "LOGOUT", "USER_DISABLE");
    }

    @Data
    public static class Risk {
        private boolean stepUpOnNewIp = true;
        private int knownIpTtlDays = 90;
    }

    @Data
    public static class Governance {
        private boolean staleAccountDisableEnabled = true;
        private int staleAccountDays = 90;
    }

    @Data
    public static class Branding {
        private String loginTitle = "ZestSSO";
        private String loginSubtitle = "统一身份认证";
        private String logoUrl;
        private String primaryColor = "#1677ff";
        private String defaultLocale = "zh-CN";
    }

    @Data
    public static class JwtRotation {
        /** JWKS 中保留的已轮换密钥数量（对标 Okta key rollover） */
        private int retiredKeysInJwks = 1;
    }

    @Data
    public static class Security {
        private int loginRateLimit = 20;
        private int loginRateWindowSeconds = 60;
        private List<String> corsAllowedOrigins = List.of("http://localhost:5173");
        /** 登出后允许跳转的 host（含 localhost、生产域名后缀） */
        private List<String> logoutRedirectHosts = List.of(
                "localhost", "127.0.0.1", "zest.wang", "zestflow.cn");
    }

    private Mail mail = new Mail();
    private PasswordReset passwordReset = new PasswordReset();
    private WebAuthn webauthn = new WebAuthn();
    private Audit audit = new Audit();
    private Backchannel backchannel = new Backchannel();
    private Webhooks webhooks = new Webhooks();
    private Risk risk = new Risk();
    private Governance governance = new Governance();
    private Branding branding = new Branding();
    private JwtRotation jwtRotation = new JwtRotation();

    @Data
    public static class WebAuthn {
        private boolean enabled = true;
        private String rpId = "localhost";
        private String rpName = "ZestSSO";
        private List<String> origins = List.of(
                "http://localhost:9000", "http://localhost:5173",
                "http://localhost:5174", "http://localhost:5175");
    }

    @Data
    public static class Mail {
        private boolean enabled = false;
        private String from = "noreply@zest.local";
        private String resetSubject = "ZestSSO 密码重置";
    }

    @Data
    public static class PasswordReset {
        /** 重置链接有效期（分钟） */
        private int tokenTtlMinutes = 30;
        private String publicBaseUrl = "http://localhost:9000";
    }

    @Data
    public static class Token {
        private int accessTokenTtl = 3600;
        private int refreshTokenTtl = 86400;
        private int idTokenTtl = 3600;
    }
}
