package cn.zest.sso.server.security;



import cn.zest.sso.server.config.SsoProperties;

import jakarta.annotation.PostConstruct;

import lombok.Getter;

import lombok.RequiredArgsConstructor;

import lombok.extern.slf4j.Slf4j;

import org.springframework.stereotype.Component;



import java.nio.file.Files;

import java.nio.file.Path;

import java.security.KeyFactory;

import java.security.KeyPair;

import java.security.KeyPairGenerator;

import java.security.interfaces.RSAPrivateKey;

import java.security.interfaces.RSAPublicKey;

import java.security.spec.PKCS8EncodedKeySpec;

import java.security.spec.X509EncodedKeySpec;

import java.util.Base64;



/**

 * JWT RSA 密钥管理器，支持从文件加载、目录自动持久化或运行时生成。

 */

@Slf4j

@Component

@RequiredArgsConstructor

public class JwtKeyManager {



    private static final String PRIVATE_FILE = "jwt-private.pem";

    private static final String PUBLIC_FILE = "jwt-public.pem";



    private final SsoProperties ssoProperties;



    @Getter

    private RSAPrivateKey privateKey;



    @Getter

    private RSAPublicKey publicKey;



    @PostConstruct

    public void init() throws Exception {

        SsoProperties.Jwt jwt = ssoProperties.getJwt();

        if (jwt.getPrivateKeyPath() != null && !jwt.getPrivateKeyPath().isBlank()

                && jwt.getPublicKeyPath() != null && !jwt.getPublicKeyPath().isBlank()) {

            loadFromFiles(jwt.getPrivateKeyPath(), jwt.getPublicKeyPath());

            log.info("JWT 密钥已从文件加载");

            return;

        }

        if (jwt.getAutoGenerateDir() != null && !jwt.getAutoGenerateDir().isBlank()) {

            Path dir = Path.of(jwt.getAutoGenerateDir());

            Path privatePath = dir.resolve(PRIVATE_FILE);

            Path publicPath = dir.resolve(PUBLIC_FILE);

            if (Files.exists(privatePath) && Files.exists(publicPath)) {

                loadFromFiles(privatePath.toString(), publicPath.toString());

                log.info("JWT 密钥已从目录加载: {}", dir.toAbsolutePath());

                return;

            }

            generateKeyPair();

            persistKeyPair(dir);

            log.info("JWT 密钥已生成并持久化到: {}", dir.toAbsolutePath());

            return;

        }

        generateKeyPair();

        log.warn("JWT 密钥为运行时生成，生产环境请配置持久化密钥文件或 auto-generate-dir");

    }



    private void loadFromFiles(String privateKeyPath, String publicKeyPath) throws Exception {

        String privatePem = Files.readString(Path.of(privateKeyPath));

        String publicPem = Files.readString(Path.of(publicKeyPath));

        this.privateKey = parsePrivateKey(privatePem);

        this.publicKey = parsePublicKey(publicPem);

    }



    private void persistKeyPair(Path dir) throws Exception {

        Files.createDirectories(dir);

        Files.writeString(dir.resolve(PRIVATE_FILE), toPrivatePem(privateKey));

        Files.writeString(dir.resolve(PUBLIC_FILE), toPublicPem(publicKey));

    }



    private void generateKeyPair() throws Exception {

        KeyPairGenerator generator = KeyPairGenerator.getInstance("RSA");

        generator.initialize(2048);

        KeyPair keyPair = generator.generateKeyPair();

        this.privateKey = (RSAPrivateKey) keyPair.getPrivate();

        this.publicKey = (RSAPublicKey) keyPair.getPublic();

    }



    private RSAPrivateKey parsePrivateKey(String pem) throws Exception {

        String content = pem.replace("-----BEGIN PRIVATE KEY-----", "")

                .replace("-----END PRIVATE KEY-----", "")

                .replaceAll("\\s", "");

        byte[] decoded = Base64.getDecoder().decode(content);

        PKCS8EncodedKeySpec spec = new PKCS8EncodedKeySpec(decoded);

        return (RSAPrivateKey) KeyFactory.getInstance("RSA").generatePrivate(spec);

    }



    private RSAPublicKey parsePublicKey(String pem) throws Exception {

        String content = pem.replace("-----BEGIN PUBLIC KEY-----", "")

                .replace("-----END PUBLIC KEY-----", "")

                .replaceAll("\\s", "");

        byte[] decoded = Base64.getDecoder().decode(content);

        X509EncodedKeySpec spec = new X509EncodedKeySpec(decoded);

        return (RSAPublicKey) KeyFactory.getInstance("RSA").generatePublic(spec);

    }



    private static String toPrivatePem(RSAPrivateKey key) {

        String encoded = Base64.getMimeEncoder(64, "\n".getBytes()).encodeToString(key.getEncoded());

        return "-----BEGIN PRIVATE KEY-----\n" + encoded + "\n-----END PRIVATE KEY-----\n";

    }



    private static String toPublicPem(RSAPublicKey key) {

        String encoded = Base64.getMimeEncoder(64, "\n".getBytes()).encodeToString(key.getEncoded());

        return "-----BEGIN PUBLIC KEY-----\n" + encoded + "\n-----END PUBLIC KEY-----\n";

    }



    public String getKeyId() {

        return ssoProperties.getJwt().getKeyId();

    }

    public void loadFromPem(String privatePem, String publicPem, String keyId) throws Exception {
        this.privateKey = parsePrivateKey(privatePem);
        this.publicKey = parsePublicKey(publicPem);
        ssoProperties.getJwt().setKeyId(keyId);
    }
}


